//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankManager {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AuditEventFile {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AuditEventFile() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BankManager.AuditEventFile", typeof(AuditEventFile).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRESKA: Ne uspesna isplata sa racuna sa brojem: {0}. Razlog: {1}.
        /// </summary>
        internal static string IsplataFailure {
            get {
                return ResourceManager.GetString("IsplataFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspesna isplata sa racuna sa brojem : {0} .
        /// </summary>
        internal static string IsplataSuccess {
            get {
                return ResourceManager.GetString("IsplataSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRESKA: Ne uspesna opomena na racunu sa brojem : {0}. Razlog: {1}.
        /// </summary>
        internal static string OpomenaFailure {
            get {
                return ResourceManager.GetString("OpomenaFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspesna opomena na racunu sa brojem : {0}.
        /// </summary>
        internal static string OpomenaSuccess {
            get {
                return ResourceManager.GetString("OpomenaSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRESKA:  Racun nije uspesno otvoren za korisnika {0}. Razlog: {1}.
        /// </summary>
        internal static string OtvoriRacunFailure {
            get {
                return ResourceManager.GetString("OtvoriRacunFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspesno otvoren racun za korisnika : {0}.
        /// </summary>
        internal static string OtvoriRacunSuccess {
            get {
                return ResourceManager.GetString("OtvoriRacunSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRESKA: Ne uspesna provera stanja racuna sa brojem: {0}. Razlog: {1}.
        /// </summary>
        internal static string ProveriStanjeFailure {
            get {
                return ResourceManager.GetString("ProveriStanjeFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspesno provereno stanje racuna sa brojem: {0}.
        /// </summary>
        internal static string ProveriStanjeSuccess {
            get {
                return ResourceManager.GetString("ProveriStanjeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRESKA: Ne uspesna uplata na racun sa brojem : {0}. Razlog: {1}.
        /// </summary>
        internal static string UplataFailure {
            get {
                return ResourceManager.GetString("UplataFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspesna uplata na racun sa brojem : {0}.
        /// </summary>
        internal static string UplataSuccess {
            get {
                return ResourceManager.GetString("UplataSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRESKA: Racun sa brojem {0} nije uspesno zatvoren. Razlog: {1}.
        /// </summary>
        internal static string ZatvoriRacunFailure {
            get {
                return ResourceManager.GetString("ZatvoriRacunFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspesno zatvoren racun sa brojem : {0}.
        /// </summary>
        internal static string ZatvoriRacunSuccess {
            get {
                return ResourceManager.GetString("ZatvoriRacunSuccess", resourceCulture);
            }
        }
    }
}
